"""Reference constants for molecular hydrogen therapy modeling."""

H2_SATURATED_MG_L = 1.57
H2_SATURATED_MM = 0.78
H2_GAS_ML_PER_L_SATURATED = 19.0

K_H2_OH_M_INV_S = 4.2e7
K_H2_ONOO_M_INV_S = 3.6e4
K_H2_SUPEROXIDE_M_INV_S = 0.0
K_H2_H2O2_M_INV_S = 0.0

GSH_PHYSIOLOGICAL_MM = 5.0
K_GSH_OH_M_INV_S = 1.0e10

AKAGI_INHALATION_HOURS_PER_DAY = 3.0
RESEARCH_GRADE_SAMPLE_SIZE_UPPER_BOUND = 200
